version: "2"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
  api:
    build: .
    ports:
      - 5000:5000
    command: python app.py --host 0.0.0.0
    environment:
      host: mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}